import type { NextPage } from 'next'
import { gql, useQuery } from '@apollo/client'
import Grid from '@mui/material/Grid';
import Paper from '@mui/material/Paper';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import TextField from '@mui/material/TextField';
import LayoutComponent from '../components/layout';
import Types from '../components/Types';
import Title from '../components/Title';

const GET_TYPES = gql `
  query GetTypes {
    types {
      id
      type_name
    }
  }
`;

const Home: NextPage = () => {
  // const { data, loading, error } = useQuery(GET_TYPES);
  // if (loading) return <p>ローディング中です</p>;
  // if (error) return <p>エラーが発生しています</p>;

  // const { types } = data;
  // return (
  //   <div className={styles.container}>
  //     <Head>
  //       <title>Create Next App</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>

  //     <main className={styles.main}>
  //       {types.map((type: {id: number; type_name: string;}) => (
  //         <div key={type.id}>Name: {type.type_name}</div>
  //       ))}
  //     </main>
  //   </div>
  // );
  return (
    <LayoutComponent>
      <Grid item xs={12} md={4} lg={3}>
        <Paper
          sx={{
            p: 2,
            display: 'flex',
            flexDirection: 'column',
            height: 150,
          }}
        >
          <Types title='口座' url='/type/1' />
        </Paper>
      </Grid>
      <Grid item xs={12} md={4} lg={3}>
        <Paper
          sx={{
            p: 2,
            display: 'flex',
            flexDirection: 'column',
            height: 150,
          }}
        >
          <Types title='その他' url='/type/2' />
        </Paper>
      </Grid>
      <Grid item xs={12}>
        <Box
          component="form"
          autoComplete="off"
          sx={{
            '& .MuiTextField-root': {
              mr: 1,
              mb: 1,
              width: {
                xs: '30ch',
                md: '50ch',
                lg: '100ch'
              }},
            }}
        >
          <Title>追加</Title>
          <TextField required id="type" label="区分" size="small" />
          <Button variant="contained">
            追加
          </Button>
        </Box>
      </Grid>
    </LayoutComponent>
    )
};

export default Home
